name: zip_search
description: A new Flutter project.
publish_to: 'none'
version: 1.3.0+11

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  bloc: ^8.1.2
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  firebase_analytics: ^11.2.0
  firebase_core: ^3.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^8.0.0
  http: ^1.1.0
  share_plus: ^7.2.2
  shared_preferences: ^2.2.1
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.3
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
